name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: Linux-Server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          scp -r ./your-app user@your-server:/path/to/deploy
          ssh user@your-server 'cd /path/to/deploy && ./deploy-script.sh'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
